// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Questioning_Data_Repositories.Context;

#nullable disable

namespace Questioning_Data_Repositories.Migrations
{
    [DbContext(typeof(WebContext))]
    [Migration("20250728072526_FixUserAnswerTblP2")]
    partial class FixUserAnswerTblP2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Answer", b =>
                {
                    b.Property<string>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("NEWID()");

                    b.Property<string>("AnswerText")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("AnswerTypes")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FkQuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TestCorrectOption")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TestOptionFour")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TestOptionOne")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TestOptionThree")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TestOptionTwo")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TruOrFalseAnswer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AnswerId");

                    b.HasIndex("AnswerId")
                        .IsUnique();

                    b.HasIndex("FkQuestionId");

                    b.HasIndex("AnswerText", "TestCorrectOption", "TruOrFalseAnswer");

                    b.ToTable("Answer", (string)null);
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Categories", b =>
                {
                    b.Property<decimal>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.HasIndex("CategoryName");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Form", b =>
                {
                    b.Property<string>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AccessCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("EndExamDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndExamTime")
                        .HasColumnType("time");

                    b.Property<decimal>("FKCategoryId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("FkUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FormTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("StartExamDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartExamTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FormId");

                    b.HasIndex("FKCategoryId");

                    b.HasIndex("FkUserId");

                    b.HasIndex("FormId")
                        .IsUnique();

                    b.HasIndex("FormTitle", "Description", "IsActive");

                    b.ToTable("Form", (string)null);
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Question", b =>
                {
                    b.Property<string>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FkUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("QuestionId");

                    b.HasIndex("FkUserId");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.HasIndex("QuestionText");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.RFormQuestion", b =>
                {
                    b.Property<string>("FormQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("FkFormId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FkQuestionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("FormQuestionId");

                    b.HasIndex("FkQuestionId");

                    b.HasIndex("FkFormId", "FkQuestionId", "FormQuestionId")
                        .IsUnique();

                    b.ToTable("RFormQuestion", (string)null);
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.UserAnswer", b =>
                {
                    b.Property<string>("UAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("AnswerDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DescriptiveAnswerText")
                        .HasMaxLength(400)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("FkAnswerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FkFormId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FkQuestionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FkUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SelectedOption")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("SelectedTrueOrFalse")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("UAnswerId");

                    b.HasIndex("FkAnswerId");

                    b.HasIndex("FkFormId");

                    b.HasIndex("FkQuestionId");

                    b.HasIndex("FkUserId", "FkQuestionId")
                        .IsUnique();

                    b.ToTable("UserAnswer", (string)null);
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.User_Permission_TBL.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RoleActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleActive");

                    b.HasIndex("RoleId", "RoleName")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.User_Permission_TBL.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Email", true);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FkRoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserProfile")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("FkRoleId");

                    b.HasIndex("FirstName", "LastName", "PhoneNumber");

                    b.HasIndex("UserId", "Email", "UserName")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Answer", b =>
                {
                    b.HasOne("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("FkQuestionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Form", b =>
                {
                    b.HasOne("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Categories", "Categories")
                        .WithMany("Forms")
                        .HasForeignKey("FKCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Questioning_Data_Repositories.DataTableEF.User_Permission_TBL.User", "User")
                        .WithMany("Forms")
                        .HasForeignKey("FkUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Categories");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Question", b =>
                {
                    b.HasOne("Questioning_Data_Repositories.DataTableEF.User_Permission_TBL.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("FkUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.RFormQuestion", b =>
                {
                    b.HasOne("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Form", "Form")
                        .WithMany("RFormQuestions")
                        .HasForeignKey("FkFormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Question", "Question")
                        .WithMany("RFormQuestions")
                        .HasForeignKey("FkQuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.UserAnswer", b =>
                {
                    b.HasOne("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Answer", "Answer")
                        .WithMany("UserAnswers")
                        .HasForeignKey("FkAnswerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Form", "Form")
                        .WithMany("UserAnswers")
                        .HasForeignKey("FkFormId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("FkQuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Questioning_Data_Repositories.DataTableEF.User_Permission_TBL.User", "User")
                        .WithMany("UserAnswers")
                        .HasForeignKey("FkUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Form");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.User_Permission_TBL.User", b =>
                {
                    b.HasOne("Questioning_Data_Repositories.DataTableEF.User_Permission_TBL.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("FkRoleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Answer", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Categories", b =>
                {
                    b.Navigation("Forms");
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Form", b =>
                {
                    b.Navigation("RFormQuestions");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.Question_Answer_TBL.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("RFormQuestions");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.User_Permission_TBL.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Questioning_Data_Repositories.DataTableEF.User_Permission_TBL.User", b =>
                {
                    b.Navigation("Forms");

                    b.Navigation("Questions");

                    b.Navigation("UserAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
